### ISSUE TITLE
Firefox windows

### ISSUE THREAD

**Issue by sonoro1234** [BrutPitt/glChAoS.P#5]
Hi Michele,

The webgl version in https://www.michelemorrone.eu/glchaosp/webGL.html shows black window.
I tried setting about:config in Firefox 74.0 64bits
    webgl.disable-angle -> true
    webgl.dxgl.enabled -> false
but nothing changed.

(It works on my android phone)

**Comment by BrutPitt** [comment]
Thanks to reporting, Victor.

First try to force a "hard" reload with CTRL-F5 (avoiding that there is a previous version in the cache)

If the problem persists, I kindly ask you to report the following information:

- The console information/error (CTRL-I to open dev-tools ==> tag: Console)
- URL window (full http address with parameters that I pass to command line)
- GPU type (model and brand) 

Thank you
Thanks

**Comment by sonoro1234** [comment]
URL
https://brutpitt.github.io/glChAoS.P/wglChAoSP/wglChAoSP.html?width=1366&height=693&maxbuffer=20&lowprec=0&intbuffer=10&tabletmode=0&glowOFF=0&lightGUI=0

console error:
Error: WebGL warning: <Create>: Refused to create WebGL2 context because of blacklist entry: wglChAoSP.js:220:55
Error: Failed to create WebGL context: WebGL creation failed: 
* Refused to create WebGL2 context because of blacklist entry: wglChAoSP.js:220:55

GPU:
Dual: Intel HD Graphics 4000 and Radeon HD 7670M
There is an interface to activate the Radeon card for each application althought Firefox does not appear

**Comment by BrutPitt** [comment]
>Error: WebGL warning: : Refused to create WebGL2 context because of blacklist entry: wglChAoSP.js:220:55
>Error: Failed to create WebGL context: WebGL creation failed:

FIrefox has inserted your graphics card in blacklist for WebGL2 (evidently there is a known bug with it)
Anyway you can test if the WebGL2 feature is supported, here:
https://webglreport.com/?v=2

> There is an interface to activate the Radeon card for each application althought Firefox does not appear

Can you select a personal executable (directly from file or process)?

In Win10 (if I remember correctly) you can this directly, going in:
Settings ==> System ==> Display ==> Graphics Settings ==> Classic App ==> button Browse ==> find firefox executable (usually C:\Program Files\Mozilla Firefox\Firefox.exe) ==> Options 

... and can select the GPU according powerSaving profile, for that application.

**Comment by sonoro1234** [comment]
> Anyway you can test if the WebGL2 feature is supported, here:
> https://webglreport.com/?v=2

Yes, It is not supported. It is not strange: It has some bugs in the driver (and will not be updated as the guys at amd told me) which are not present in ubuntu drivers!!

> Can you select a personal executable (directly from file or process)?

from file.

Well, this is not glChAoS.P issue but my card issue... so I will close.

Thanks again Michele
